"""Added pets and owner tables

Revision ID: 25c4032b7c7c
Revises: b967dae7703f
Create Date: 2023-07-08 23:17:41.484811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c4032b7c7c'
down_revision = 'b967dae7703f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('phone', sa.Integer(), nullable=True),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_foreign_key(None, 'pets', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_table('owners')
    # ### end Alembic commands ###
