"""Added handler and jobs tables

Revision ID: fb02b8a71d9e
Revises: 25c4032b7c7c
Create Date: 2023-07-09 01:22:58.580547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb02b8a71d9e'
down_revision = '25c4032b7c7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handlers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'pets', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_table('jobs')
    op.drop_table('handlers')
    # ### end Alembic commands ###
